### ISSUE TITLE
Callbacks for on_break_complete and on_work_complete

### ISSUE THREAD

**Issue by khalidchawtany** [dbinagi/nomodoro#1]
Thanks for this plugin.

Is there any way to hook into  `on_break_complete` and `on_work_complete`?
I want to play a sound or show a floating window in the above cases.
A callback for the above events would make this possible.

**Comment by dbinagi** [comment]
Hi @khalidchawtany sure, thats a nice idea, let me see if i can include the callbacks and let me know how you include sound. 
I wanted to make something like that at first but decided to leave it for a second iteration

**Comment by khalidchawtany** [comment]
Thank you very much 🥇
