### ISSUE TITLE
Problem with on_xx_complete

### ISSUE THREAD

**Issue by ahmedaljaali** [dbinagi/nomodoro#3]
Hello, How are you? I hope you're doing well!

I have a problem where 'on_work_complete' executes when I complete a break
Here is what I'm trying to do:
![2022-08-10_22:17:28](https://user-images.githubusercontent.com/82327047/184001151-a1a32db1-2bf7-44c3-807c-5b63bdb19715.jpg)

**Comment by dbinagi** [comment]
Hi, how are you. I will try to look into detail whats going on, i dont know about the notify plugin, i will try it. In the meantime, whats the failure in this case? Could it be it has something to do with `vim.notify` VS `notify` only?

**Comment by ahmedaljaali** [comment]
I tried to remove notify, but still it calls 'on_work_complete' when break is finished, like it doesn't know 'on_break_complete' is there.

**Comment by dbinagi** [comment]
I think there is a problem right now if you put the same time on Break that on Work, could you try put different numbers there to see if callbacks are working good from your side. 
I plan to make a fix on that but just to be sure thats just the issue. Didnt expect to have same time on those fields, hehe.

**Comment by ahmedaljaali** [comment]
You are right!, when I changed their values it starts to work correctly
