### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by joaovfsousa** [dbinagi/nomodoro#6]
I noticed the repo doesn't have a license. Can I clone and do some modifications for my own use?
I would like to sync the timer between multiple neovim instances. I don't know if that interests you, if so I can submit a PR to add this functionality in this repo.

**Comment by dbinagi** [comment]
Hi! If you would like to add a PR thats great as i think that could be a great feature to have, if i can help you anyway just DM me, i will add a license to the project but will be MIT license, nice reminder i never did. Regards.
